-- MySQL Script generated by MySQL Workbench
-- Sat Jan 31 18:12:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lgs_orders
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lgs_orders
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lgs_orders` ;
USE `lgs_orders` ;

-- -----------------------------------------------------
-- Table `lgs_orders`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lgs_orders`.`order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cid` BIGINT NOT NULL,
  `order_number` VARCHAR(45) NULL,
  `date_entered` DATETIME NOT NULL,
  `date_updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lgs_orders`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lgs_orders`.`order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `lgs_orders`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
